import { defineConfig } from 'vite';
import { resolve } from 'node:path';

// base './' keeps every asset path relative, so the build works from the
// domain root without leaking root-absolute /assets/ paths.
// ms/index.html is GENERATED by scripts/build-ms.mjs from index.html + i18n/ms.json.
export default defineConfig({
  base: './',
  build: {
    outDir: 'dist',
    assetsInlineLimit: 0,
    rollupOptions: {
      input: { main: resolve(import.meta.dirname, 'index.html'), ms: resolve(import.meta.dirname, 'ms/index.html') },
    },
  },
});
